
package Users;

import config.OTPGenerator;
import config.DbConnect;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class UseRecoveryEmailChoice extends javax.swing.JFrame {

    private String generatedOtp;

    /**
     * Creates new form MobileNumber
     */
    public UseRecoveryEmailChoice() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        con = new javax.swing.JButton();
        m12 = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        con1 = new javax.swing.JButton();
        m1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RECOVER YOUR PASSWORD ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 610, 116));

        jButton3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButton3.setText("BACK");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        con.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        con.setText("Request");
        con.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });
        jPanel5.add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 130, 40));
        jPanel5.add(m12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 280, 40));

        na.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        na.setEnabled(false);
        jPanel5.add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 580, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Verify OTP");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 110, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Name:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, 40));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Email is auto-generated based on the email you registered");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 540, 20));

        con1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        con1.setText("CONTINUE");
        con1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        con1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con1ActionPerformed(evt);
            }
        });
        jPanel5.add(con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 190, 40));

        m1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        m1.setEnabled(false);
        jPanel5.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 580, 40));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setText("Email:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 870, 360));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("SEND OTP VIA EMAIL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, "Are you sure you wanna discard this recovery process?", "Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();

            UserRecoveryOption loginPage = new UserRecoveryOption();
            loginPage.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
     DbConnect dbc = new DbConnect();
    config.Session sess = config.Session.getInstance(); 

    
    String recipientEmail = sess.getemail(); 
    if (recipientEmail == null || recipientEmail.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Invalid Email.");
        return; 
    }

    generatedOtp = OTPGenerator.generateOTP(4); 

    System.out.println("Generated OTP: " + generatedOtp); 

    try {
        sendEmail(recipientEmail, generatedOtp); 
    } catch (Exception e) {
        e.printStackTrace(); 
    }}
private void sendEmail(String toEmail, String otp) {
    
      final String fromEmail = "malacastec123@gmail.com"; 
    final String appPassword = "lrtp csmu gjal hfsy"; 

    Properties props = new Properties();
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "465");
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.ssl.enable", "true");

    Session session = Session.getInstance(props, new javax.mail.Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(fromEmail, appPassword);
        }
    });

    try {
        Message message = new MimeMessage(session);
        message.setFrom(new InternetAddress(fromEmail));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
        message.setSubject("LIBRARY MANAGEMENT SYSTEM - OTP Verification");

        // HTML styled message with a title
        String htmlMessage = ""
            + "<div style='font-family: Arial, sans-serif; font-size: 14px;'>"
            + "<h2 style='color: #333333;'>LIBRARY MANAGEMENT SYSTEM VERIFICATION CODE</h2>"
            + "<hr style='border: 1px solid #ccc;'>"
            + "<p>This is a one-time password. For security reasons, please do not share this OTP with anyone.</p>"
            + "<p>If you did not request this OTP, please ignore this message.</p>"
            + "<p><strong>Your OTP is: </strong>"
            + "<span style='font-size: 18px; color: blue; font-weight: bold;'>" + otp + "</span></p>"
            + "<hr style='border: 1px solid #ccc;'>"
            + "</div>";

        message.setContent(htmlMessage, "text/html; charset=utf-8"); 

        Transport.send(message);
        System.out.println("Email sent successfully!");

    } catch (MessagingException e) {
        e.printStackTrace(); 
    }
    }//GEN-LAST:event_conActionPerformed

    private void con1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con1ActionPerformed
     String inputOtp = m12.getText().trim(); 
    System.out.println("Input OTP: " + inputOtp); 
    System.out.println("Stored OTP: " + this.generatedOtp); 

    if (inputOtp.equals(this.generatedOtp)) { 
        JOptionPane.showMessageDialog(this, "OTP Verified!");
        UserResetPassword urp = new UserResetPassword();
        urp.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid OTP!");
        
    }
    }//GEN-LAST:event_con1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
   config.Session sess = config.Session.getInstance();

    
    if (sess.getusername()== null) {
        JOptionPane.showMessageDialog(null, "No account found, find your account first!");
        UserForgotPass ufp = new UserForgotPass();
        ufp.setVisible(true);
        this.dispose();
    } else {
               
        na.setText(sess.getusername());
        m1.setText(sess.getemail());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UseRecoveryEmailChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UseRecoveryEmailChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UseRecoveryEmailChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UseRecoveryEmailChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UseRecoveryEmailChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton con;
    private javax.swing.JButton con1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m12;
    private javax.swing.JTextField na;
    // End of variables declaration//GEN-END:variables
}
