/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Users;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author II
 */
public class UserSecurity extends javax.swing.JFrame {

    /**
     * Creates new form UserSecurity
     */
    public UserSecurity() {
         setUndecorated(true);
        initComponents();
    }
private boolean hasShownPinReminder = false;
    private boolean isPinCreationOpen = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        sq = new javax.swing.JLabel();
        PIN = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 20, 29));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Security");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 190, 29));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-110, 0, 890, 70);

        note.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        note.setText("<html>Note: It is advisable that you add a security measures <br>to protect user data and in case of password loss . </html>");
        jPanel1.add(note);
        note.setBounds(20, 80, 510, 42);

        sq.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        sq.setForeground(new java.awt.Color(102, 102, 255));
        sq.setText("Security Question");
        sq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sqMouseExited(evt);
            }
        });
        jPanel1.add(sq);
        sq.setBounds(220, 220, 360, 60);

        PIN.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        PIN.setForeground(new java.awt.Color(102, 102, 255));
        PIN.setText("PIN");
        PIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PINMouseExited(evt);
            }
        });
        jPanel1.add(PIN);
        PIN.setBounds(340, 300, 120, 60);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 430, 780, 100);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setText("Select Security measures:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 170, 360, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PINMouseClicked
     if (!isPinCreationOpen) { 
        isPinCreationOpen = true; 
        UserPINcreation uc = new UserPINcreation();
        
        
        uc.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                isPinCreationOpen = false; 
            }
        });

        uc.setVisible(true); 
    }
    }//GEN-LAST:event_PINMouseClicked

    private void PINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PINMouseEntered
       PIN.setCursor(new Cursor(Cursor.HAND_CURSOR));
       PIN.setForeground(Color.BLACK);
    }//GEN-LAST:event_PINMouseEntered

    private void PINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PINMouseExited
        PIN.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        PIN.setForeground(Color.BLUE);
    }//GEN-LAST:event_PINMouseExited

    private void sqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqMouseClicked
     UserSQcreation usq = new UserSQcreation();
     usq.setVisible(true);
    }//GEN-LAST:event_sqMouseClicked

    private void sqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqMouseEntered
        sq.setCursor(new Cursor(Cursor.HAND_CURSOR));
        sq.setForeground(Color.BLACK);
    }//GEN-LAST:event_sqMouseEntered

    private void sqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqMouseExited
      sq.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
      sq.setForeground(Color.BLUE);
    }//GEN-LAST:event_sqMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
 

        
        this.dispose();
        
    
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
      jLabel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
      jLabel1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSecurity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel note;
    public javax.swing.JLabel sq;
    // End of variables declaration//GEN-END:variables
}
