
package Users;

import config.DbConnect;
import config.Session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class UserChangePassForm extends javax.swing.JFrame {
 
    
    public UserChangePassForm() {
        initComponents();
    }
private boolean verifyCurrentPassword(String currentPass) {
    boolean isValid = false;

    try {
        
        DbConnect db = new DbConnect();
        Connection conn = db.getConnection(); 

        String query = "SELECT RegPass FROM users WHERE u_id = ?";
        PreparedStatement stmt = conn.prepareStatement(query);

        stmt.setInt(1, Session.getInstance().getuid()); 

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            String dbPass = rs.getString("RegPass");
            isValid = dbPass.equals(currentPass); 
        }

        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }

    return isValid;
}
private boolean updatePassword(String newPass) {
    boolean isUpdated = false;
    
    try {
        
        DbConnect db = new DbConnect();
        Connection conn = db.getConnection(); 

        String query = "UPDATE users SET RegPass = ? WHERE u_id = ?";
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setString(1, newPass); 
        stmt.setInt(2, Session.getInstance().getuid());

        int rows = stmt.executeUpdate();
        if (rows > 0) {
            isUpdated = true;
        }

        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    return isUpdated;
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Interface1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        acc_lname_user = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        acc_cn_user = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        acc_cn_user2 = new javax.swing.JLabel();
        acc_cn_user3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        acc_cn_user4 = new javax.swing.JLabel();
        acc_cn_user5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        acc_cn_user6 = new javax.swing.JLabel();
        acc_cn_user7 = new javax.swing.JLabel();
        reenterPasswordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        currentPasswordField = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnChangePassword = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Interface1.setBackground(new java.awt.Color(102, 0, 0));
        Interface1.setForeground(new java.awt.Color(102, 102, 102));
        Interface1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setBackground(new java.awt.Color(204, 0, 51));
        BackButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel3.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/ACCOUNTT.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 60));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setText("Change Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 241, 50));

        Interface1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(204, 0, 51));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 190, 50));

        Interface1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 650));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setText("Current Password:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 240, 50));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setText("New Password:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_lname_user.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_lname_user.setText("User!");
        jPanel6.add(acc_lname_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));

        newPasswordField.setBorder(null);
        newPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordFieldActionPerformed(evt);
            }
        });
        jPanel6.add(newPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 40));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 350, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_cn_user.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_cn_user.setText("User!");
        jPanel7.add(acc_cn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_cn_user2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_cn_user2.setText("User!");
        jPanel8.add(acc_cn_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));

        acc_cn_user3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_cn_user3.setText("User!");
        jPanel8.add(acc_cn_user3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 40));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_cn_user4.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_cn_user4.setText("User!");
        jPanel9.add(acc_cn_user4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));

        acc_cn_user5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_cn_user5.setText("User!");
        jPanel9.add(acc_cn_user5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_cn_user6.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_cn_user6.setText("User!");
        jPanel10.add(acc_cn_user6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));

        acc_cn_user7.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        acc_cn_user7.setText("User!");
        jPanel10.add(acc_cn_user7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 40));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 40));

        reenterPasswordField.setBorder(null);
        reenterPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reenterPasswordFieldActionPerformed(evt);
            }
        });
        jPanel7.add(reenterPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, 310, 40));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 350, 40));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setText("Re-enter Pass:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 190, 50));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentPasswordField.setEditable(false);
        currentPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        currentPasswordField.setText("jPasswordField1");
        currentPasswordField.setBorder(null);
        jPanel13.add(currentPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, 300, 40));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 350, 40));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 30, 40));

        btnChangePassword.setBackground(new java.awt.Color(204, 0, 51));
        btnChangePassword.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnChangePassword.setText("Change");
        btnChangePassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jPanel4.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 190, 50));

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 30, 40));

        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 30, 40));

        Interface1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 730, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Interface1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Interface1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        UserAccount ua = new UserAccount();
        ua.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
 String currentPass = String.valueOf(currentPasswordField.getPassword());
    String newPass = String.valueOf(newPasswordField.getPassword());
    String reenterPass = String.valueOf(reenterPasswordField.getPassword());

    if (currentPass.isEmpty() || newPass.isEmpty() || reenterPass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!newPass.equals(reenterPass)) {
        JOptionPane.showMessageDialog(this, "New passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    if (verifyCurrentPassword(currentPass)) {
        
        if (updatePassword(newPass)) {
            JOptionPane.showMessageDialog(this, "Password changed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Error updating password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Incorrect current password!", "Error", JOptionPane.ERROR_MESSAGE);
    }       
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (currentPasswordField == null) {
            System.out.println("acc_ps_user is null");
            return;
        }

        
        if (jCheckBox1.isSelected()) {
            currentPasswordField.setEchoChar((char) 0); 
        } else {
            currentPasswordField.setEchoChar('*'); 
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         Session sess = Session.getInstance();
       
       if(sess.getuid() == 0){
           JOptionPane.showMessageDialog(null,"No account found , Log in First!");
           Loginform lf = new Loginform();
           lf.setVisible(true);
           this.dispose();
       
       }
       
       currentPasswordField.setText(""+sess.getPassword());
       currentPasswordField.setEchoChar('*');
       
       
    }//GEN-LAST:event_formWindowActivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void newPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordFieldActionPerformed

    private void reenterPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reenterPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reenterPasswordFieldActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) { 
        newPasswordField.setEchoChar((char) 0);
    } else {
        newPasswordField.setEchoChar('*');
    }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()) { 
        reenterPasswordField.setEchoChar((char) 0);
    } else {
        reenterPasswordField.setEchoChar('*');
    }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserChangePassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserChangePassForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Interface1;
    private javax.swing.JLabel acc_cn_user;
    private javax.swing.JLabel acc_cn_user2;
    private javax.swing.JLabel acc_cn_user3;
    private javax.swing.JLabel acc_cn_user4;
    private javax.swing.JLabel acc_cn_user5;
    private javax.swing.JLabel acc_cn_user6;
    private javax.swing.JLabel acc_cn_user7;
    private javax.swing.JLabel acc_lname_user;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JPasswordField currentPasswordField;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JPasswordField reenterPasswordField;
    // End of variables declaration//GEN-END:variables
}
