/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Users;

import Internal.AvailableBooks;
import Internal.BorrowBook;

import Internal.BorrowerSignup;
import Internal.UserBorrowedBooks;
import config.DbConnect;
import config.Logger;
import config.Session;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.JButton;
import javax.swing.JOptionPane;


public class UserDashboard extends javax.swing.JFrame {

   
    public UserDashboard() {
        setUndecorated(true);
        initComponents();
       
    customizeButton(Logoutbutton);
    
    
    
    customizeButton(AccountDetails);
    checkAndApplyPenalties();
    }
private void customizeButton(JButton button) {
   button.setOpaque(true);
button.setBorderPainted(false);
button.setFocusPainted(false);
button.setBackground(new Color(139, 0, 0)); 
button.setForeground(Color.WHITE);
button.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 14));

   
    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(new Color(0, 102, 204)); 
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(new Color(139, 0, 0)); 
        }
    });
}
    private void checkAndApplyPenalties() {
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/malacaste_db", "root", "")) {
       String query = "SELECT bb.br_id, bb.b_fk, bb.borrowdays, t.borrow_date, u.u_id " +
               "FROM Borrowedbooks bb " +
               "JOIN transactions t ON bb.b_fk = t.book_id AND t.return_date IS NULL " +
               "JOIN borrowers b ON bb.br_id = b.br_id " +
               "JOIN users u ON b.u_id = u.u_id " +
               "WHERE u.u_id = ?";


        PreparedStatement ps = conn.prepareStatement(query);
        ps.setInt(1, Session.getInstance().getuid());
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            int userId = rs.getInt("u_id");
            int bookId = rs.getInt("b_fk");
            int allowedDays = rs.getInt("borrowdays");
            LocalDateTime borrowDate = rs.getTimestamp("borrow_date").toLocalDateTime();

            long daysBorrowed = java.time.Duration.between(borrowDate, LocalDateTime.now()).toDays();

            if (daysBorrowed > allowedDays) {
                int overdueDays = (int)(daysBorrowed - allowedDays);
                double penalty = overdueDays * 5.0; 

               
                String checkPenalty = "SELECT * FROM penalties WHERE user_id = ? AND book_id = ? AND status = 'unpaid'";
                PreparedStatement psCheck = conn.prepareStatement(checkPenalty);
                psCheck.setInt(1, userId);
                psCheck.setInt(2, bookId);
                ResultSet rsCheck = psCheck.executeQuery();

                if (!rsCheck.next()) {
                    String insertPenalty = "INSERT INTO penalties (user_id, book_id, overdue_days, penalty_amount) VALUES (?, ?, ?, ?)";
                    PreparedStatement psInsert = conn.prepareStatement(insertPenalty);
                    psInsert.setInt(1, userId);
                    psInsert.setInt(2, bookId);
                    psInsert.setInt(3, overdueDays);
                    psInsert.setDouble(4, penalty);
                    psInsert.executeUpdate();
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Interface = new javax.swing.JPanel();
        Interface1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Logoutbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AccountDetails = new javax.swing.JButton();
        acc_fname_user = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        borrowedbooks = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Interface.setBackground(new java.awt.Color(0, 0, 0));
        Interface.setForeground(new java.awt.Color(102, 102, 102));
        Interface.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Interface1.setBackground(new java.awt.Color(102, 102, 102));
        Interface1.setForeground(new java.awt.Color(102, 102, 102));
        Interface1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logoutbutton.setBackground(new java.awt.Color(204, 0, 51));
        Logoutbutton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Logoutbutton.setText("LOGOUT");
        Logoutbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(Logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WELCOME TO THE LIBRARY!");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 380, 50));

        AccountDetails.setBackground(new java.awt.Color(204, 0, 51));
        AccountDetails.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        AccountDetails.setText("Account ");
        AccountDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AccountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(AccountDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 140, 30));

        acc_fname_user.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        acc_fname_user.setForeground(new java.awt.Color(255, 255, 255));
        acc_fname_user.setText("User!");
        jPanel2.add(acc_fname_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 290, 30));

        Interface1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lets Get Started!");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, -1));

        jPanel8.setBackground(new java.awt.Color(204, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/customerService.png"))); // NOI18N
        jLabel8.setText("Customer Service");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 170, -1));

        Interface1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 650));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        borrowedbooks.setBackground(new java.awt.Color(204, 0, 0));
        borrowedbooks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrowedbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowedbooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrowedbooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrowedbooksMouseExited(evt);
            }
        });
        borrowedbooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/icons8_Books_26px.png"))); // NOI18N
        jLabel11.setText("View Borrowed Books");
        borrowedbooks.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        jPanel4.add(borrowedbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 220, 50));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setText("STAY TUNED!");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        Register.setBackground(new java.awt.Color(204, 0, 0));
        Register.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterMouseExited(evt);
            }
        });
        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/icons8_Books_26px.png"))); // NOI18N
        jLabel9.setText("Verify Borrower");
        Register.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 30));

        jPanel4.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 50));

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel7.setText("Features:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, -1));

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/icons8_Book_Shelf_50px.png"))); // NOI18N
        jLabel2.setText("Available Books");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, 50));

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/icons8_Books_26px.png"))); // NOI18N
        jLabel5.setText("Borrow Book");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 190, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 50));

        jPanel7.setBackground(new java.awt.Color(204, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/icons8_Book_26px.png"))); // NOI18N
        jLabel6.setText("Return Book");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 190, 28));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/unnamed.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 650, 510));

        jLabel12.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel12.setText("Verify:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, -1));

        Interface1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 730, 580));

        Interface.add(Interface1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Interface, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Interface, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbuttonActionPerformed
      int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, "Are you sure you want to logout?", "Logout Confirmation",
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        
        try (Connection conn = new DbConnect().getConnection()) {
            Session sess = Session.getInstance();
            int userId = sess.getuid();
            String username = sess.getusername();

            Logger logger = new Logger(conn);
            logger.logAdd(userId, "User logged out: " + username);
        } catch (Exception e) {
            System.err.println("Failed to log logout action: " + e.getMessage());
        }

        this.dispose(); 
        
        Loginform loginPage = new Loginform(); 
        loginPage.setVisible(true);
    }
    }//GEN-LAST:event_LogoutbuttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
       
       if(sess.getuid() == 0){
           JOptionPane.showMessageDialog(null,"No account found , Log in First!");
           Loginform lf = new Loginform();
           lf.setVisible(true);
           this.dispose();
       
       }
       acc_fname_user.setText(sess.getFname() +" "+  sess.getLname());
       
    }//GEN-LAST:event_formWindowActivated

    private void AccountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountDetailsActionPerformed
        UserAccount ua = new UserAccount();
        ua.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccountDetailsActionPerformed

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    jPanel6.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
       jPanel6.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    jPanel6.setBackground(Color.RED); 
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
       jPanel5.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    jPanel5.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
       jPanel5.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    jPanel5.setBackground(Color.RED); 
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
         jPanel7.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    jPanel7.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    jPanel7.setBackground(Color.RED); 
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        jPanel8.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
        jPanel8.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
      jPanel8.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
      jPanel8.setBackground(Color.RED); 
    }//GEN-LAST:event_jLabel8MouseExited

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
       jPanel8.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); 
       jPanel8.setBackground(Color.RED); 
    }//GEN-LAST:event_jPanel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jPanel8.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
        jPanel8.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
       AvailableBooks bb = new AvailableBooks();
       bb.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
      int uid = Session.getInstance().getuid();

    try {
      
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/malacaste_db",  
            "root",                           
            ""                         
        );

      
        String sql = "SELECT * FROM borrowers WHERE u_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, uid);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
           
            BorrowBook nf = new BorrowBook();
            nf.setVisible(true);
            this.dispose(); 
        } else {
           
            JOptionPane.showMessageDialog(null, "Access denied. You must be a borrower to proceed.");
        }

        conn.close();

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
    }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseClicked
         BorrowerSignup bb = new BorrowerSignup();
        bb.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_RegisterMouseClicked

    private void RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseEntered
         Register.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
       Register.setBackground(Color.WHITE); 
    }//GEN-LAST:event_RegisterMouseEntered

    private void RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseExited
       Register.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); 
        Register.setBackground(Color.RED); 
    }//GEN-LAST:event_RegisterMouseExited

    private void borrowedbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowedbooksMouseClicked
       UserBorrowedBooks ubb = new UserBorrowedBooks();
       ubb.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_borrowedbooksMouseClicked

    private void borrowedbooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowedbooksMouseEntered
       borrowedbooks.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
       borrowedbooks.setBackground(Color.WHITE); 
    }//GEN-LAST:event_borrowedbooksMouseEntered

    private void borrowedbooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowedbooksMouseExited
       borrowedbooks.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); 
       borrowedbooks.setBackground(Color.RED); 
    }//GEN-LAST:event_borrowedbooksMouseExited

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        UserBorrowedBooks ubb = new UserBorrowedBooks();
        ubb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountDetails;
    private javax.swing.JPanel Interface;
    private javax.swing.JPanel Interface1;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel acc_fname_user;
    private javax.swing.JPanel borrowedbooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
