
package Users;

import config.Session;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author II
 */
public class UserRecoveryOption extends javax.swing.JFrame {

    
    public UserRecoveryOption() {
         
        setUndecorated(true);
        
        initComponents();
        customizeButton(BackButton1);
        
        
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                
            }
        });
        addMouseMotionListener(new java.awt.event.MouseAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                
            }
        });
         
     
    }
    
    
private void customizeButton(JButton button) {
   button.setOpaque(true);
   button.setBorderPainted(false);
   button.setFocusPainted(false);
   button.setBackground(new Color(51, 51, 255)); 
   button.setForeground(Color.WHITE);


   
    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(new Color(102, 153, 255)); 
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(new Color(51, 51, 255)); 
        }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Interface1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        titlelabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PIN = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SecurityQ = new javax.swing.JLabel();
        titlelabel4 = new javax.swing.JLabel();
        USER = new javax.swing.JLabel();
        titlelabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mnumber = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Interface1.setBackground(new java.awt.Color(102, 102, 102));
        Interface1.setForeground(new java.awt.Color(102, 102, 102));
        Interface1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton1.setBackground(new java.awt.Color(204, 204, 204));
        BackButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BackButton1.setText("Back to Login");
        BackButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(BackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 210, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scc.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        exit.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 20, 20));

        titlelabel5.setBackground(new java.awt.Color(0, 0, 0));
        titlelabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        titlelabel5.setForeground(new java.awt.Color(255, 255, 255));
        titlelabel5.setText("ACCOUNT RECOVERY PAGE");
        jPanel2.add(titlelabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 380, 50));

        Interface1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanel4.setBackground(new java.awt.Color(239, 239, 239));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/4b620eef47445bd3e7ca1afa68b8396a.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1050, 80));

        PIN.setBackground(new java.awt.Color(0, 0, 0));
        PIN.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        PIN.setForeground(new java.awt.Color(51, 51, 255));
        PIN.setText("PIN");
        PIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PINMouseExited(evt);
            }
        });
        jPanel4.add(PIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 70, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/ACCOUNTT.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, 60));

        SecurityQ.setBackground(new java.awt.Color(0, 0, 0));
        SecurityQ.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        SecurityQ.setForeground(new java.awt.Color(51, 51, 255));
        SecurityQ.setText("Security Question");
        SecurityQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SecurityQMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SecurityQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SecurityQMouseExited(evt);
            }
        });
        jPanel4.add(SecurityQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 241, 60));

        titlelabel4.setBackground(new java.awt.Color(0, 0, 0));
        titlelabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        titlelabel4.setText("Account name:");
        jPanel4.add(titlelabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, 50));

        USER.setBackground(new java.awt.Color(0, 0, 0));
        USER.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        USER.setForeground(new java.awt.Color(51, 51, 255));
        USER.setText("USER");
        jPanel4.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 400, 50));

        titlelabel6.setBackground(new java.awt.Color(0, 0, 0));
        titlelabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        titlelabel6.setText("Recovery Option :");
        jPanel4.add(titlelabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 240, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("#");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 40, -1));

        mnumber.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        mnumber.setForeground(new java.awt.Color(51, 51, 255));
        mnumber.setText("Mobile number");
        mnumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnumberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnumberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnumberMouseExited(evt);
            }
        });
        jPanel4.add(mnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/adadsdadwd.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 330, 260));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 240));

        Interface1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Interface1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Interface1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton1ActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, "Are you sure you wanna discard this recovery process?", "Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();

            Loginform loginPage = new Loginform();
            loginPage.setVisible(true);
        }
    }//GEN-LAST:event_BackButton1ActionPerformed

    private void SecurityQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecurityQMouseExited
        SecurityQ.setCursor( new Cursor(Cursor.DEFAULT_CURSOR));
        SecurityQ.setForeground(Color.BLUE);
    }//GEN-LAST:event_SecurityQMouseExited

    private void SecurityQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecurityQMouseEntered
        SecurityQ.setCursor( new Cursor(Cursor.HAND_CURSOR));
        SecurityQ.setForeground(Color.WHITE);
    }//GEN-LAST:event_SecurityQMouseEntered

    private void SecurityQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecurityQMouseClicked
       UserRecoverySQchoice ursc = new UserRecoverySQchoice();
       ursc.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_SecurityQMouseClicked

    private void PINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PINMouseExited
        PIN.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        PIN.setForeground(Color.BLUE);
    }//GEN-LAST:event_PINMouseExited

    private void PINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PINMouseEntered
        PIN.setCursor(new Cursor (Cursor.HAND_CURSOR));
        PIN.setForeground(Color.WHITE);
    }//GEN-LAST:event_PINMouseEntered

    private void PINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PINMouseClicked
     UserRecoveryPINchoice urpc = new UserRecoveryPINchoice();
     urpc.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_PINMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();

    
    if (sess.getusername() == null) {
        JOptionPane.showMessageDialog(null, "No account found, find your account first!");
        UserForgotPass ufp = new UserForgotPass();
        ufp.setVisible(true);
        this.dispose();
    } else {
        
        USER.setText(sess.getFname() + " " + sess.getLname());
    
    }
    }//GEN-LAST:event_formWindowActivated

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_exitMouseExited

    private void mnumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnumberMouseClicked

    private void mnumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnumberMouseEntered
        mnumber.setCursor(new Cursor(Cursor.HAND_CURSOR));
        mnumber.setForeground(Color.WHITE);
    }//GEN-LAST:event_mnumberMouseEntered

    private void mnumberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnumberMouseExited
       mnumber.setCursor( new Cursor  (Cursor.DEFAULT_CURSOR));
       mnumber.setForeground( Color.BLUE);
    }//GEN-LAST:event_mnumberMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRecoveryOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRecoveryOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRecoveryOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRecoveryOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRecoveryOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton1;
    private javax.swing.JPanel Interface1;
    private javax.swing.JLabel PIN;
    private javax.swing.JLabel SecurityQ;
    private javax.swing.JLabel USER;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel mnumber;
    private javax.swing.JLabel titlelabel4;
    private javax.swing.JLabel titlelabel5;
    private javax.swing.JLabel titlelabel6;
    // End of variables declaration//GEN-END:variables
}
